### ISSUE TITLE
Remove security functionality for youth accounts

### ISSUE THREAD

**Issue by mcglander** [enes-th/discord-invite-tracker#4]
How remove that?

**Comment by enes-th** [comment]
Hello,

Iit is not yet possible to remove this feature via a command. 
However, you can remove it directly from the code. 

Follow these steps:
1. Go to the `guildMemberAdd` and `guildMemberRemove` files that are located on the `events` folder
2. Delete line **34** in these files. The line should contain this code:
```js
if (Date.now() - member.user.createdTimestamp < 1000 * 60 * 60 * 24 * 10) return youngAccount(member, inviter, client, false);
```
3. Restart your bot

Now your bot will no longer apply this young account verification.
