### ISSUE TITLE
Support for a /myinvitelink command?

### ISSUE THREAD

**Issue by DawgZter** [enes-th/discord-invite-tracker#6]
Thanks for working on this project!

I just wanted to request a new command called /myinvitelink that generates (or recalls) a user's unique invite link.

I think this would be great from a UX standpoint instead of using having to manually generate an invite link.

**Comment by DawgZter** [comment]
I've just dropped you a friend req :) @enes-th

**Comment by enes-th** [comment]
The command has been added on [version 1.1.2](https://github.com/enes-th/discord-invite-tracker/releases/tag/v1.1.2)!
